Repository netobserv/network-observability-cli, pull requests merged in 2024-06, with the labels that each got.

#42 Allow custom image at run time
  commands/netobserv
Labels: lgtm, approved

#43 [backport] allow custom image at run time (#42)
  commands/netobserv
Labels: lgtm, approved

#48 NETOBSERV-1678: allow agent image configuration
  Makefile
  commands/netobserv
  res/flow-capture.yml
  res/packet-capture.yml
  scripts/functions.sh
  scripts/inject.sh
Labels: lgtm, approved, jira/valid-reference

#49 Backport of NETOBSERV-1678
  Makefile
  commands/netobserv
  res/flow-capture.yml
  res/packet-capture.yml
  scripts/functions.sh
  scripts/inject.sh
Labels: lgtm, approved

#51 NETOBSERV-1707: move to go 1.22
  .github/workflows/pull_request.yml
  .github/workflows/pull_request_e2e.yml
  .github/workflows/push_image.yml
  .github/workflows/push_image_pr.yml
  .github/workflows/release.yml
  .golangci.yml
  Dockerfile
Labels: lgtm, approved, jira/valid-reference

#53 Add .ci-operator.yaml
  .ci-operator.yaml
Labels: lgtm

#54 NETOBSERV-1617: use filter with packets capture feature
  commands/netobserv
  docs/netobserv_cli_packets_config.md
  e2e/capture_test.go
  e2e/script_test.go
  res/flow-capture.yml
  res/packet-capture.yml
  scripts/functions.sh
Labels: lgtm, approved, jira/valid-reference
