Repository netobserv/network-observability-cli, pull requests merged in 2024-12, with the labels that each got.

#101 NETOBSERV-1906 add nodeSelector
  res/flow-capture.yml
  res/packet-capture.yml
  scripts/functions.sh
Labels: lgtm, approved

#92 add mocks to cli
  .mk/dev.mk
  Makefile
  cmd/flow_capture.go
  cmd/mocks.go
  cmd/packet_capture.go
  cmd/root.go
  go.mod
Labels: lgtm, approved, no-qe

#121 NETOBSERV-1909 filter regexes
  res/flow-capture.yml
  res/packet-capture.yml
  scripts/functions.sh
Labels: lgtm, approved

#102 NETOBSERV-1907 run in background
  Dockerfile
  cmd/flow_capture.go
  cmd/packet_capture.go
  cmd/root.go
  cmd/root_test.go
  commands/netobserv
  e2e/script_test.go
  res/service-account.yml
  scripts/functions.sh
Labels: lgtm, approved

#105 NETOBSERV-1580 Reuse frontend config
  .mk/dev.mk
  Makefile
  cmd/config.go
  cmd/config.yaml
  cmd/flow_capture.go
  cmd/flow_capture_test.go
  cmd/map_format.go
  cmd/map_format_test.go
  cmd/packet_capture.go
  cmd/root.go
  cmd/root_test.go
  e2e/capture_test.go
  go.mod
  scripts/update-config.sh
Labels: lgtm, approved

#103 NETOBSERV-1908 Be able to customize namespace
  Dockerfile
  commands/netobserv
  res/collector-service.yml
  res/flow-capture.yml
  res/namespace.yml
  res/packet-capture.yml
  res/service-account.yml
  scripts/functions.sh
Labels: lgtm, approved

#124 NETOBSERV-1578 subnets labels
  scripts/functions.sh
Labels: lgtm, approved

#128 NETOBSERV-2005: Allow populaiting only single filter rules for cli usecase
  res/flow-capture.yml
  res/packet-capture.yml
  scripts/functions.sh
Labels: lgtm, approved, jira/valid-reference

#138 Adding version label in downstream image build
  Dockerfile.downstream
Labels: lgtm, approved

#139 Misc-fixes
  Dockerfile.downstream
  Makefile
Labels: lgtm, approved

#142 add netns volume mount to avoid agent warning when it starts
  res/flow-capture.yml
Labels: lgtm, approved
