Repository netobserv/network-observability-cli, pull requests merged in 2024-09, with the labels that each got.

#87 NETOBSERV-1792: Added update-build script to add downstream labels
  .tekton/network-observability-cli-bin-pull-request.yaml
  .tekton/network-observability-cli-bin-push.yaml
  .tekton/network-observability-cli-container-pull-request.yaml
  .tekton/network-observability-cli-container-push.yaml
  hack/update-build.sh
Labels: lgtm, approved, jira/valid-reference

#90 NETOBSERV-1882 test e2e faillure
  .github/workflows/pull_request_e2e.yml
  cmd/flow_capture.go
  cmd/packet_capture.go
  cmd/root.go
  e2e/capture_test.go
  e2e/cluster/kind.go
  e2e/common.go
  scripts/kind-cluster.sh
Labels: lgtm, approved, no-qe

#84 NETOBSERV-1803: Allow flow filtering for L4 protocols using two ports
  res/flow-capture.yml
  res/packet-capture.yml
  scripts/functions.sh
Labels: lgtm, approved, jira/valid-reference

#93 OSDOCS-11821 help & doc cleanup
  commands/netobserv
  docs/netobserv_cli.adoc
  scripts/functions.sh
  scripts/generate-doc.sh
Labels: lgtm, approved

#91 NETOBSERV-1850 fix cli enrichment issue
  cmd/packet_capture.go
  cmd/root.go
Labels: lgtm
