Repository netobserv/network-observability-cli, pull requests merged in 2024-07, with the labels that each got.

#62 NETOBSERV-1749: fix flows and packets arg processing
  scripts/functions.sh
Labels: ok-to-test, lgtm, approved, jira/valid-reference

#60 NETOBSERV-1693 Prompt for copying files on exit
  commands/netobserv
  e2e/common.go
  scripts/functions.sh
Labels: lgtm, approved

#59 NETOBSERV-1684 Auto teardown after some time / number of flows / packets
  cmd/flow_capture.go
  cmd/packet_capture.go
  cmd/root.go
  commands/netobserv
  docs/netobserv_cli_flows_config.md
  docs/netobserv_cli_packets_config.md
  e2e/script_test.go
  res/flow-capture.yml
  res/packet-capture.yml
  scripts/functions.sh
Labels: lgtm, approved, qe-approved

#65 NETOBSERV-1693 Prompt for copying files on exit followup
  commands/netobserv
  docs/netobserv_cli_flows_config.md
  docs/netobserv_cli_packets_config.md
  scripts/functions.sh
Labels: ok-to-test, lgtm, approved, qe-approved
