Repository netobserv/network-observability-cli, pull requests merged in 2025-02, with the labels that each got.

#168 Add release info
  docs/RELEASE.md
Labels: lgtm, approved

#169 NETOBSERV-2112: Make build FIPS compliant
  Dockerfile
  Dockerfile.downstream
Labels: lgtm, approved, jira/valid-reference

#170 NETOBSERV-2112: Make build FIPS compliant [1.8 backport]
  Dockerfile
  Dockerfile.downstream
Labels: lgtm, approved, jira/valid-reference

#167 [Backport] NETOBSERV-2107: fix service monitor quotes
  res/metric-capture.yml
  res/service-account.yml
  res/service-monitor.yml
  scripts/functions.sh
Labels: ok-to-test, lgtm, approved, jira/valid-reference, qe-approved

#166 NETOBSERV-2107: fix service monitor quotes
  res/metric-capture.yml
  res/service-account.yml
  res/service-monitor.yml
  scripts/functions.sh
Labels: ok-to-test, lgtm, approved, jira/valid-reference, qe-approved

#176 [Backport] NETOBSERV-2107 Disable worload metrics
  res/metrics-pipeline-config.json
Labels: ok-to-test, lgtm, approved

#174 NETOBSERV-2107 disable dns & rtt workload metrics
  res/metrics-pipeline-config.json
Labels: lgtm, approved

#190 NETOBSERV-2123: remove 1.8 unsupported features from cli[BP to 1.8]
  scripts/functions.sh
  scripts/help.sh
Labels: lgtm, approved, jira/valid-reference

#191 bump ose cli image
  Dockerfile.downstream
Labels: lgtm

#192 [Backport] bump ose cli image
  Dockerfile.downstream
Labels: lgtm, approved

#196 Add missing description label to downstream containerfile [BP]
  Dockerfile.downstream
Labels: lgtm, approved

#199 fix args and version
  Dockerfile.downstream
Labels: lgtm, approved
