Repository netobserv/network-observability-cli, pull requests merged in 2025-05, with the labels that each got.

#285 NETOBSERV-2187: adapt regex to new query language in flp
  commands/netobserv
  docs/netobserv_cli.adoc
  e2e/integration-tests/integration_test.go
  e2e/script_test.go
  scripts/functions.sh
  scripts/help.sh
Labels: ok-to-test, approved, breaking-changes, jira/valid-reference, qe-approved

#286 NETOBSERV-2243 Add IPsec support to netobserv CLI
  cmd/config.yaml
  cmd/options.go
  docs/netobserv_cli.adoc
  e2e/script_test.go
  go.mod
  go.sum
  res/flow-capture.yml
  scripts/functions.sh
  scripts/help.sh
  vendor/github.com/gorilla/websocket/README.md
  vendor/github.com/gorilla/websocket/client.go
  vendor/github.com/gorilla/websocket/compression.go
  vendor/github.com/gorilla/websocket/conn.go
  vendor/github.com/gorilla/websocket/proxy.go
  vendor/github.com/gorilla/websocket/server.go
  vendor/github.com/gorilla/websocket/tls_handshake.go
  vendor/github.com/gorilla/websocket/tls_handshake_116.go
  vendor/github.com/gorilla/websocket/x_net_proxy.go
  vendor/modules.txt
Labels: approved, qe-approved

#289 NETOBSERV-2117 CLI metrics options
  docs/netobserv_cli.adoc
  e2e/script_test.go
  res/metrics-pipeline-config.json
  res/service-monitor.yml
  scripts/functions.sh
  scripts/generate-doc.sh
  scripts/help.sh
Labels: lgtm, approved, qe-approved

#209 NETOBSERV-2118 add missing sampling and exclude interfaces options
  docs/netobserv_cli.adoc
  scripts/functions.sh
  scripts/generate-doc.sh
  scripts/help.sh
Labels: ok-to-test, lgtm, approved, qe-approved, needs-review

#300 Config update
  cmd/config.yaml
Labels: lgtm, approved, needs-review
