Repository netobserv/network-observability-cli, pull requests merged in 2025-01, with the labels that each got.

#141 move to go 1.23
  .github/workflows/pull_request.yml
  .github/workflows/pull_request_e2e.yml
  .github/workflows/push_image.yml
  .github/workflows/push_image_pr.yml
  .github/workflows/release.yml
  .golangci.yml
  Dockerfile
  Dockerfile.downstream
  Makefile
  cmd/flow_capture.go
  cmd/flow_capture_test.go
  cmd/flow_db.go
  cmd/packet_capture.go
  cmd/root.go
  e2e/cluster/kind.go
Labels: lgtm, approved

#136 Nit: better text asking for copying
  scripts/functions.sh
Labels: lgtm, approved, no-qe

#106 NETOBSERV-1911 CLI metrics
  README.md
  commands/netobserv
  docs/netobserv_cli.adoc
  e2e/script_test.go
  img/metrics-dashboard.png
  img/packet-table.png
  res/metric-capture.yml
  res/namespace.yml
  res/service-monitor.yml
  scripts/functions.sh
  scripts/generate-doc.sh
  scripts/inject.sh
Labels: lgtm, approved, qe-approved

#144 NETOBSERV-2016 refactor display options
  cmd/flow_capture.go
  cmd/flow_capture_test.go
  cmd/map_format.go
  cmd/options.go
Labels: lgtm, approved, no-qe

#153 skip ci faillure on coverage upload issues
  .github/workflows/pull_request.yml
Labels: lgtm, approved, no-qe

#145 NETOBSERV-2020 check node selector
  scripts/functions.sh
Labels: ok-to-test, lgtm, approved, qe-approved

#150 NETOBSERV-1578 Fix bash issues on macos
  Makefile
  commands/netobserv
  scripts/dependencies_check.sh
  scripts/generate-doc.sh
  scripts/inject.sh
  scripts/krew.sh
  scripts/update-config.sh
Labels: ok-to-test, lgtm, approved, qe-approved

#143 NETOBSERV-2030: deploy on master nodes
  res/flow-capture.yml
  res/packet-capture.yml
Labels: ok-to-test, lgtm, approved, jira/valid-reference, qe-approved

#147 NETOBSERV-2047: Add peerCIDR flow filtering support
  res/flow-capture.yml
  res/packet-capture.yml
  scripts/functions.sh
Labels: lgtm, approved, jira/valid-reference, no-qe

#146 NETOBSERV-2021: Improve UX
  Makefile
  README.md
  cmd/config.yaml
  cmd/flow_capture.go
  cmd/flow_capture_test.go
  cmd/map_format.go
  cmd/options.go
  commands/netobserv
  docs/netobserv_cli.adoc
  e2e/script_test.go
  res/collector-pipeline-config.json
  res/flow-capture.yml
  res/flow-filter.json
  res/metric-capture.yml
  res/metrics-pipeline-config.json
  res/packet-capture.yml
  scripts/functions.sh
  scripts/generate-doc.sh
  scripts/help.sh
  scripts/inject.sh
  scripts/kind-cluster.sh
Labels: lgtm, approved, jira/valid-reference, qe-approved

#159 [Backport] NETOBSERV-2021: Improve UX
  Makefile
  README.md
  cmd/config.yaml
  cmd/flow_capture.go
  cmd/flow_capture_test.go
  cmd/map_format.go
  cmd/options.go
  commands/netobserv
  docs/netobserv_cli.adoc
  e2e/script_test.go
  res/collector-pipeline-config.json
  res/flow-capture.yml
  res/flow-filter.json
  res/metric-capture.yml
  res/metrics-pipeline-config.json
  res/packet-capture.yml
  scripts/functions.sh
  scripts/generate-doc.sh
  scripts/help.sh
  scripts/inject.sh
  scripts/kind-cluster.sh
Labels: lgtm, approved, jira/valid-reference
