Repository netobserv/network-observability-cli, pull requests merged in 2025-03, with the labels that each got.

#206 update linter to avoid memory leak
  Makefile
Labels: lgtm, approved, no-qe

#211 gracefully fail on which check
  scripts/dependencies_check.sh
Labels: ok-to-test, lgtm, approved

#213 bump-1.9.0
  Dockerfile.downstream
Labels: lgtm, approved

#214 remove useless enable filter option in doc
  docs/netobserv_cli.adoc
  scripts/generate-doc.sh
Labels: lgtm, approved, no-qe

#201 NETOBSERV-2133 CLI flows JSON
  cmd/flow_capture.go
  scripts/functions.sh
Labels: ok-to-test, lgtm, approved, qe-approved

#219 NETOBSERV-2150: add license and readme to downstream container
  .tekton/network-observability-cli-container-pull-request.yaml
  .tekton/network-observability-cli-container-push.yaml
  .tekton/pipeline-ref.yaml
  Dockerfile-args.downstream
  Dockerfile.downstream
  README.downstream
Labels: jira/valid-reference, no-qe

#195 NETOBSERV-2114: automate krew releases
  .github/workflows/release.yml
  .krew.yaml
  Makefile
  scripts/krew.sh
Labels: jira/valid-reference, no-qe

#224 README: getting started section with Krew
  README.md
Labels: lgtm
